version: '3'

services:
  db:
    image: postgres:11.2
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app: &app_base
    build: .
    command: /bin/sh -c "rm -f ./tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    environment:
      RAILS_ENV: development
    depends_on:
      - db
  spring:
    <<: *app_base
    command: bin/spring server
    ports: []

volumes:
  postgres-data:
